"""
Export service for generating reports in various formats
"""

import json
import io
from typing import Dict, Any
from datetime import datetime
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from models import SummaryResponse

class ExportService:
    """Service for exporting summaries in various formats"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles for PDF generation"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkblue
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.darkblue
        ))
        
        self.styles.add(ParagraphStyle(
            name='RiskLevel',
            parent=self.styles['Normal'],
            fontSize=14,
            spaceAfter=6,
            alignment=TA_CENTER,
            textColor=colors.white,
            backColor=colors.red
        ))
    
    def export_to_pdf(self, summary_data: SummaryResponse) -> bytes:
        """Export summary to PDF format"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72,
                              topMargin=72, bottomMargin=18)
        
        story = []
        
        # Title
        story.append(Paragraph("Censys AI Agent - Host Analysis Report", self.styles['CustomTitle']))
        story.append(Spacer(1, 12))
        
        # Header information
        header_data = [
            ['Host IP:', summary_data.host_ip],
            ['Analysis Date:', datetime.fromisoformat(summary_data.timestamp.replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M:%S UTC')],
            ['Processing Time:', f"{summary_data.processing_time_ms}ms" if summary_data.processing_time_ms else "N/A"]
        ]
        
        header_table = Table(header_data, colWidths=[2*inch, 4*inch])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (1, 0), (1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(header_table)
        story.append(Spacer(1, 20))
        
        # Process each summary type
        for summary_type, summary in summary_data.summaries.items():
            story.append(Paragraph(f"{summary_type.title()} Summary", self.styles['SectionHeader']))
            
            if summary_type == 'executive':
                story = self._add_executive_summary_to_pdf(story, summary)
            elif summary_type == 'technical':
                story = self._add_technical_summary_to_pdf(story, summary)
            elif summary_type == 'security':
                story = self._add_security_summary_to_pdf(story, summary)
            
            story.append(Spacer(1, 20))
        
        # Footer
        story.append(Spacer(1, 20))
        story.append(Paragraph(
            f"Report generated by Censys AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            self.styles['Normal']
        ))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    def _add_executive_summary_to_pdf(self, story, summary):
        """Add executive summary content to PDF"""
        # Risk level
        risk_color = self._get_risk_color(summary.risk_level)
        risk_style = ParagraphStyle(
            name='RiskLevel',
            parent=self.styles['Normal'],
            fontSize=14,
            spaceAfter=12,
            alignment=TA_CENTER,
            textColor=colors.white,
            backColor=risk_color
        )
        story.append(Paragraph(f"Risk Level: {summary.risk_level}", risk_style))
        
        # Business impact
        story.append(Paragraph("Business Impact:", self.styles['Heading3']))
        story.append(Paragraph(summary.business_impact, self.styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Key findings
        story.append(Paragraph("Key Findings:", self.styles['Heading3']))
        for finding in summary.key_findings:
            story.append(Paragraph(f"• {finding}", self.styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Recommendations
        story.append(Paragraph("Recommendations:", self.styles['Heading3']))
        for rec in summary.recommendations:
            story.append(Paragraph(f"• {rec}", self.styles['Normal']))
        
        if summary.compliance_notes:
            story.append(Spacer(1, 12))
            story.append(Paragraph("Compliance Notes:", self.styles['Heading3']))
            for note in summary.compliance_notes:
                story.append(Paragraph(f"• {note}", self.styles['Normal']))
        
        return story
    
    def _add_technical_summary_to_pdf(self, story, summary):
        """Add technical summary content to PDF"""
        # Service analysis
        story.append(Paragraph("Service Analysis:", self.styles['Heading3']))
        service_data = [
            ['Total Services', str(summary.service_analysis.total_services)],
            ['Open Ports', ', '.join(map(str, summary.service_analysis.open_ports))],
            ['Protocols', ', '.join(summary.service_analysis.protocols)]
        ]
        
        service_table = Table(service_data, colWidths=[2*inch, 4*inch])
        service_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (1, 0), (1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(service_table)
        story.append(Spacer(1, 12))
        
        # Configuration issues
        if summary.configuration_issues:
            story.append(Paragraph("Configuration Issues:", self.styles['Heading3']))
            for issue in summary.configuration_issues:
                story.append(Paragraph(f"• {issue}", self.styles['Normal']))
            story.append(Spacer(1, 12))
        
        # Technical recommendations
        story.append(Paragraph("Technical Recommendations:", self.styles['Heading3']))
        for rec in summary.technical_recommendations:
            story.append(Paragraph(f"• {rec}", self.styles['Normal']))
        
        return story
    
    def _add_security_summary_to_pdf(self, story, summary):
        """Add security summary content to PDF"""
        # Vulnerability summary
        story.append(Paragraph("Vulnerability Summary:", self.styles['Heading3']))
        vuln_data = [
            ['Total Vulnerabilities', str(summary.vulnerability_summary.total_vulns)],
            ['Critical', str(summary.vulnerability_summary.critical)],
            ['High', str(summary.vulnerability_summary.high)],
            ['Medium', str(summary.vulnerability_summary.medium)],
            ['Low', str(summary.vulnerability_summary.low)],
            ['Known Exploited Vulnerabilities', str(summary.vulnerability_summary.kev_count)]
        ]
        
        vuln_table = Table(vuln_data, colWidths=[2*inch, 1*inch])
        vuln_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (1, 0), (1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(vuln_table)
        story.append(Spacer(1, 12))
        
        # Exploitability assessment
        story.append(Paragraph("Exploitability Assessment:", self.styles['Heading3']))
        story.append(Paragraph(summary.exploitability_assessment, self.styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Critical issues
        if summary.critical_issues:
            story.append(Paragraph("Critical Issues:", self.styles['Heading3']))
            for issue in summary.critical_issues:
                story.append(Paragraph(f"• {issue}", self.styles['Normal']))
            story.append(Spacer(1, 12))
        
        # Remediation priority
        story.append(Paragraph("Remediation Priority:", self.styles['Heading3']))
        for priority in summary.remediation_priority:
            story.append(Paragraph(f"• {priority}", self.styles['Normal']))
        
        return story
    
    def _get_risk_color(self, risk_level: str) -> colors.Color:
        """Get color for risk level"""
        risk_colors = {
            'CRITICAL': colors.red,
            'HIGH': colors.orange,
            'MEDIUM': colors.yellow,
            'LOW': colors.green,
            'UNKNOWN': colors.grey
        }
        return risk_colors.get(risk_level.upper(), colors.grey)
    
    def export_to_json(self, summary_data: SummaryResponse) -> str:
        """Export summary to JSON format"""
        return summary_data.model_dump_json(indent=2)
    
    def export_to_txt(self, summary_data: SummaryResponse) -> str:
        """Export summary to plain text format"""
        lines = []
        lines.append("=" * 60)
        lines.append("CENSYS AI AGENT - HOST ANALYSIS REPORT")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Host IP: {summary_data.host_ip}")
        lines.append(f"Analysis Date: {datetime.fromisoformat(summary_data.timestamp.replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append(f"Processing Time: {summary_data.processing_time_ms}ms" if summary_data.processing_time_ms else "Processing Time: N/A")
        lines.append("")
        
        for summary_type, summary in summary_data.summaries.items():
            lines.append("-" * 40)
            lines.append(f"{summary_type.upper()} SUMMARY")
            lines.append("-" * 40)
            lines.append("")
            
            if summary_type == 'executive':
                lines.append(f"Risk Level: {summary.risk_level}")
                lines.append("")
                lines.append("Business Impact:")
                lines.append(summary.business_impact)
                lines.append("")
                lines.append("Key Findings:")
                for finding in summary.key_findings:
                    lines.append(f"  • {finding}")
                lines.append("")
                lines.append("Recommendations:")
                for rec in summary.recommendations:
                    lines.append(f"  • {rec}")
                if summary.compliance_notes:
                    lines.append("")
                    lines.append("Compliance Notes:")
                    for note in summary.compliance_notes:
                        lines.append(f"  • {note}")
            
            elif summary_type == 'technical':
                lines.append("Service Analysis:")
                lines.append(f"  Total Services: {summary.service_analysis.total_services}")
                lines.append(f"  Open Ports: {', '.join(map(str, summary.service_analysis.open_ports))}")
                lines.append(f"  Protocols: {', '.join(summary.service_analysis.protocols)}")
                lines.append("")
                if summary.configuration_issues:
                    lines.append("Configuration Issues:")
                    for issue in summary.configuration_issues:
                        lines.append(f"  • {issue}")
                    lines.append("")
                lines.append("Technical Recommendations:")
                for rec in summary.technical_recommendations:
                    lines.append(f"  • {rec}")
            
            elif summary_type == 'security':
                lines.append("Vulnerability Summary:")
                lines.append(f"  Total Vulnerabilities: {summary.vulnerability_summary.total_vulns}")
                lines.append(f"  Critical: {summary.vulnerability_summary.critical}")
                lines.append(f"  High: {summary.vulnerability_summary.high}")
                lines.append(f"  Medium: {summary.vulnerability_summary.medium}")
                lines.append(f"  Low: {summary.vulnerability_summary.low}")
                lines.append(f"  Known Exploited Vulnerabilities: {summary.vulnerability_summary.kev_count}")
                lines.append("")
                lines.append("Exploitability Assessment:")
                lines.append(summary.exploitability_assessment)
                lines.append("")
                if summary.critical_issues:
                    lines.append("Critical Issues:")
                    for issue in summary.critical_issues:
                        lines.append(f"  • {issue}")
                    lines.append("")
                lines.append("Remediation Priority:")
                for priority in summary.remediation_priority:
                    lines.append(f"  • {priority}")
            
            lines.append("")
        
        lines.append("=" * 60)
        lines.append(f"Report generated by Censys AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("=" * 60)
        
        return "\n".join(lines)
